//--- FIRST BLOCK -----------------------------
export const IS_COMPLETED_TYPE_ONE = "IS_COMPLETED_TYPE_ONE";
export const IS_COMPLETED_SECH_ONE = "IS_COMPLETED_SECH_ONE";
export const IS_COMPLETED_INPUT_ONE = "IS_COMPLETED_INPUT_ONE";
export const IS_COMPLETED_BLOCK_ONE = "IS_COMPLETED_BLOCK_ONE";
export const BLOCK_ONE_READY = "BLOCK_ONE_READY";
//--- TWO BLOCK -------------------------------
export const IS_COMPLETED_TYPE_TWO = "IS_COMPLETED_TYPE_TWO";
export const IS_COMPLETED_SECH_TWO = "IS_COMPLETED_SECH_TWO";
export const IS_COMPLETED_INPUT_TWO = "IS_COMPLETED_INPUT_TWO";
export const IS_COMPLETED_BLOCK_TWO = "IS_COMPLETED_BLOCK_TWO";
export const BLOCK_TWO_READY = "BLOCK_TWO_READY";
//--- THREE BLOCK -----------------------------
export const IS_COMPLETED_TYPE_THREE = "IS_COMPLETED_TYPE_THREE";
export const IS_COMPLETED_SECH_THREE = "IS_COMPLETED_SECH_THREE";
export const IS_COMPLETED_INPUT_THREE = "IS_COMPLETED_INPUT_THREE";
export const IS_COMPLETED_BLOCK_THREE = "IS_COMPLETED_BLOCK_THREE";
export const BLOCK_THREE_READY = "BLOCK_THREE_READY";
//--- FOUR BLOCK ------------------------------
export const IS_COMPLETED_TYPE_FOUR = "IS_COMPLETED_TYPE_FOUR";
export const IS_COMPLETED_SECH_FOUR = "IS_COMPLETED_SECH_FOUR";
export const IS_COMPLETED_INPUT_FOUR = "IS_COMPLETED_INPUT_FOUR";
export const IS_COMPLETED_BLOCK_FOUR = "IS_COMPLETED_BLOCK_FOUR";
export const BLOCK_FOUR_READY = "BLOCK_FOUR_READY";
//--- FIVE BLOCK ------------------------------
export const IS_COMPLETED_TYPE_FIVE = "IS_COMPLETED_TYPE_FIVE";
export const IS_COMPLETED_SECH_FIVE = "IS_COMPLETED_SECH_FIVE";
export const IS_COMPLETED_INPUT_FIVE = "IS_COMPLETED_INPUT_FIVE";
export const IS_COMPLETED_BLOCK_FIVE = "IS_COMPLETED_BLOCK_FIVE";
export const BLOCK_FIVE_READY = "BLOCK_FIVE_READY";
//--- SIX BLOCK -------------------------------
export const IS_COMPLETED_TYPE_SIX = "IS_COMPLETED_TYPE_SIX";
export const IS_COMPLETED_SECH_SIX = "IS_COMPLETED_SECH_SIX";
export const IS_COMPLETED_INPUT_SIX = "IS_COMPLETED_INPUT_SIX";
export const IS_COMPLETED_BLOCK_SIX = "IS_COMPLETED_BLOCK_SIX";
export const BLOCK_SIX_READY = "BLOCK_SIX_READY";

export const CHANGE_LENG_VALUE = "CHANGE_LENG_VALUE";
export const CHANGE_TYPE_TUBE_VALUE = "CHANGE_TYPE_TUBE_VALUE";
export const CHANGE_OUTPUT_FINAL_VALUE = "CHANGE_OUTPUT_FINAL_VALUE";
